-- Flota: familias de máquinas, las máquinas mismas y su historial de mantenimiento.

CREATE TABLE equipment_types (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                       VARCHAR(40)    NOT NULL,
    name                       VARCHAR(120)   NOT NULL,
    maintenance_interval_hours NUMERIC(12, 2) NOT NULL,
    description                VARCHAR(400),
    active                     BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at                 TIMESTAMP      NOT NULL,
    updated_at                 TIMESTAMP      NOT NULL,
    CONSTRAINT uk_equipment_types_code UNIQUE (code),
    CONSTRAINT ck_equipment_types_interval_positive CHECK (maintenance_interval_hours > 0)
);

CREATE TABLE equipment (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                        VARCHAR(40)    NOT NULL,
    equipment_type_id           BIGINT         NOT NULL,
    hour_meter                  NUMERIC(12, 2) NOT NULL,
    maintenance_threshold_hours NUMERIC(12, 2) NOT NULL,
    status                      VARCHAR(20)    NOT NULL,
    last_maintenance_hour_meter NUMERIC(12, 2),
    last_maintenance_date       DATE,
    version                     BIGINT         NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP      NOT NULL,
    updated_at                  TIMESTAMP      NOT NULL,
    CONSTRAINT uk_equipment_code UNIQUE (code),
    CONSTRAINT fk_equipment_type FOREIGN KEY (equipment_type_id) REFERENCES equipment_types (id),
    -- Un horómetro solo avanza, así que nunca puede ser negativo.
    CONSTRAINT ck_equipment_hour_meter_non_negative CHECK (hour_meter >= 0),
    CONSTRAINT ck_equipment_status CHECK (status IN ('AVAILABLE', 'BLOCKED', 'IN_MAINTENANCE', 'OUT_OF_SERVICE'))
);

CREATE INDEX idx_equipment_type ON equipment (equipment_type_id);
CREATE INDEX idx_equipment_status ON equipment (status);

CREATE TABLE maintenance_records (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id         BIGINT         NOT NULL,
    -- Copia del código tal como era: una traza de auditoría debe sobrevivir a que una máquina se renumere.
    equipment_code       VARCHAR(40)    NOT NULL,
    performed_on         DATE           NOT NULL,
    hour_meter           NUMERIC(12, 2) NOT NULL,
    threshold_hours      NUMERIC(12, 2) NOT NULL,
    overrun_hours        NUMERIC(12, 2) NOT NULL,
    next_threshold_hours NUMERIC(12, 2) NOT NULL,
    responsible          VARCHAR(120)   NOT NULL,
    observations         VARCHAR(1000),
    created_at           TIMESTAMP      NOT NULL,
    updated_at           TIMESTAMP      NOT NULL,
    CONSTRAINT fk_maintenance_records_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
    CONSTRAINT ck_maintenance_records_overrun_non_negative CHECK (overrun_hours >= 0)
);

CREATE INDEX idx_maintenance_records_equipment ON maintenance_records (equipment_id, performed_on DESC);
