-- Personal: los operadores y aquello que cada uno está habilitado a conducir.

CREATE TABLE operators (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number VARCHAR(20) NOT NULL,
    first_name      VARCHAR(80) NOT NULL,
    last_name       VARCHAR(80) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uk_operators_document UNIQUE (document_number),
    CONSTRAINT ck_operators_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE certifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id         BIGINT       NOT NULL,
    equipment_type_id   BIGINT       NOT NULL,
    -- Copias de la familia, para que leer una certificación nunca obligue a entrar al contexto de activos.
    equipment_type_code VARCHAR(40)  NOT NULL,
    equipment_type_name VARCHAR(120) NOT NULL,
    issued_on           DATE         NOT NULL,
    expires_on          DATE         NOT NULL,
    CONSTRAINT fk_certifications_operator FOREIGN KEY (operator_id) REFERENCES operators (id) ON DELETE CASCADE,
    CONSTRAINT fk_certifications_equipment_type FOREIGN KEY (equipment_type_id) REFERENCES equipment_types (id),
    -- Una certificación por operador y familia: una renovación reemplaza la vigencia, no agrega una
    -- fila, de modo que "¿está certificado?" siempre tiene exactamente una respuesta.
    CONSTRAINT uk_certifications_operator_type UNIQUE (operator_id, equipment_type_id),
    CONSTRAINT ck_certifications_window CHECK (expires_on >= issued_on)
);

CREATE INDEX idx_certifications_operator ON certifications (operator_id);
CREATE INDEX idx_certifications_expiry ON certifications (expires_on);
