-- Operaciones: turnos, la dotación asociada a cada uno y la traza de las asignaciones forzadas.

CREATE TABLE shifts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          DATE           NOT NULL,
    journey       VARCHAR(10)    NOT NULL,
    planned_hours NUMERIC(12, 2) NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    closed_at     TIMESTAMP,
    notes         VARCHAR(500),
    -- Bloqueo optimista sobre toda la dotación: dos supervisores editando el mismo turno chocan aquí
    -- en lugar de pisarse entre ellos.
    version       BIGINT         NOT NULL DEFAULT 0,
    created_at    TIMESTAMP      NOT NULL,
    updated_at    TIMESTAMP      NOT NULL,
    CONSTRAINT uk_shifts_date_journey UNIQUE (date, journey),
    CONSTRAINT ck_shifts_journey CHECK (journey IN ('DAY', 'NIGHT')),
    CONSTRAINT ck_shifts_status CHECK (status IN ('PLANNED', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_shifts_planned_hours_positive CHECK (planned_hours > 0)
);

CREATE INDEX idx_shifts_date ON shifts (date);
CREATE INDEX idx_shifts_status_date ON shifts (status, date);

CREATE TABLE assignments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id              BIGINT       NOT NULL,
    operator_id           BIGINT       NOT NULL,
    operator_name         VARCHAR(160) NOT NULL,
    operator_document     VARCHAR(20)  NOT NULL,
    equipment_id          BIGINT       NOT NULL,
    equipment_code        VARCHAR(40)  NOT NULL,
    equipment_type_id     BIGINT       NOT NULL,
    equipment_type_name   VARCHAR(120) NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    worked_hours          NUMERIC(12, 2),
    closure_note          VARCHAR(500),
    risk_reason           VARCHAR(500),
    -- Traza de auditoría, que solo se llena cuando un supervisor autorizó una asignación que
    -- incumplía las reglas.
    authorized_by_user_id BIGINT,
    authorized_by_name    VARCHAR(120),
    authorization_reason  VARCHAR(500),
    authorized_at         TIMESTAMP,
    overridden_rule_codes VARCHAR(500),
    CONSTRAINT fk_assignments_shift FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignments_operator FOREIGN KEY (operator_id) REFERENCES operators (id),
    CONSTRAINT fk_assignments_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
    CONSTRAINT ck_assignments_status CHECK (status IN ('SCHEDULED', 'AT_RISK', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT ck_assignments_worked_hours CHECK (worked_hours IS NULL OR worked_hours >= 0),
    -- Una asignación forzada no vale nada sin la firma que la explica.
    CONSTRAINT ck_assignments_authorization_complete CHECK (
        authorized_by_user_id IS NULL
            OR (authorization_reason IS NOT NULL AND authorized_at IS NOT NULL)
    )
);

-- Reglas de negocio 6 y 7, garantizadas por la propia base de datos.
--
-- Son índices parciales por una razón concreta: una asignación cancelada libera a su operador y a su
-- máquina para que entre un reemplazo, mientras la fila cancelada sobrevive como historia. Esta es la
-- garantía que se sostiene incluso si dos supervisores envían en el mismo instante y ambos pasan la
-- verificación en memoria: una de las dos escrituras falla y se le pide refrescar.
CREATE UNIQUE INDEX uk_assignments_shift_operator
    ON assignments (shift_id, operator_id)
    WHERE status <> 'CANCELLED';

CREATE UNIQUE INDEX uk_assignments_shift_equipment
    ON assignments (shift_id, equipment_id)
    WHERE status <> 'CANCELLED';

CREATE INDEX idx_assignments_equipment ON assignments (equipment_id);
CREATE INDEX idx_assignments_operator ON assignments (operator_id);
CREATE INDEX idx_assignments_status ON assignments (status);
